UBUNTU=karmic lucid maverick
UBUNTURELEASE=$(UBUNTU:%=ubuntu-%)

.PHONY:: git-push ubuntu $(UBUNTURELEASE)

ubuntu:
	for r in $(UBUNTURELEASE); do $(MAKE) $$r ; done
	@echo "\nYou can now build the Ubuntu source package with\n"
	@echo "\tmake packsrc\n"

#$(UBUNTURELEASE):
#	debchange -c debian/changelog.karmic -D karmic -v $(VERSION)~$(@:ubuntu-%=%)~npalix1 "New release $(VERSION)"
IDX?=1

ubuntu-karmic:
	debchange -c debian/changelog.karmic -D karmic -v $(VERSION)~910npalix$(IDX) "New release $(VERSION)"

ubuntu-lucid:
	debchange -c debian/changelog.lucid -D lucid -v $(VERSION)~1004npalix$(IDX) "New release $(VERSION)"

ubuntu-maverick:
	debchange -c debian/changelog.maverick -D maverick -v $(VERSION)~1010npalix$(IDX) "New release $(VERSION)"

ubuntu-UNRELEASED:
	debchange --create -c debian/changelog.$(@:ubuntu-%=%) -D UNRELEASED \
		  -v $(VERSION)~npalix$(IDX) "New release $(VERSION)"        \
		  --package $(TARGET)

git-push:
	git push
	git push forge

debian:
	$(MAKE) -C debian

debians:
	$(MAKE) -C debian signed
